version: "3.8"

services:
  postgres:
    environment:
      POSTGRES_DB: interview_platform_dev
      POSTGRES_PASSWORD: dev_password_123
    ports:
      - "5432:5432"

  redis:
    command: redis-server --appendonly yes --requirepass dev_redis_123
    ports:
      - "6379:6379"

  pgadmin:
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@interview-platform.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    profiles: []

  # Development-only services
  mailhog:
    image: mailhog/mailhog:latest
    container_name: interview-platform-mailhog
    restart: unless-stopped
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI
    networks:
      - interview-network

  # Development database seeding service
  seed-dev:
    image: node:18-alpine
    container_name: interview-platform-seed-dev
    restart: "no"
    working_dir: /app
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgresql://postgres:dev_password_123@postgres:5432/interview_platform_dev
      NODE_ENV: development
    networks:
      - interview-network
    depends_on:
      postgres:
        condition: service_healthy
    profiles:
      - seed
    command:
      ["sh", "-c", "npm install && npx prisma migrate deploy && npm run seed"]
